### ISSUE TITLE
Sign in with alternative Azure account

### ISSUE THREAD

**Issue by AErmie** [prchanda/MonDiag#1]
I encountered this error when attempting to sign in to an alternative Azure account.

**Reproduce Steps:**
1. From a corporate device, launch the MonDiag tool. This will auto-assume you're using your corporate credentials.
2. Click the Sign In button (an image of a person in the top right corner)
3. Enter your non-corporate credentials (i.e. @outlook.com)

![mondiag-error01](https://user-images.githubusercontent.com/10376796/46759250-e55f6980-cc9c-11e8-88f3-efd9aa75a304.png)

A similar error is produced when you close the Sign In prompt without completing the sign in process: 
![mondiag-error02](https://user-images.githubusercontent.com/10376796/46759590-c7decf80-cc9d-11e8-8a12-326ef3314aac.png)

The Event View provides the following information:

Log Name:      Application
Source:        Application Error
Date:          10/10/2018 3:01:35 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WIN-G8C2WZ0NU2.corp.avanade.org
Description:
Faulting application name: MonDiag.exe, version: 2.0.0.0, time stamp: 0x5bb653fd
Faulting module name: KERNELBASE.dll, version: 10.0.16299.611, time stamp: 0x966d0f68
Exception code: 0xe0434352
Fault offset: 0x00104172
Faulting process id: 0x1c64
Faulting application start time: 0x01d460cba3528ade
Faulting application path: C:\Users\adin.p.ermie\Downloads\MonDiag\MonDiag.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 966f1fe9-9573-4d88-a6de-fc5b8d41ad39
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2018-10-10T19:01:35.766599200Z" />
    <EventRecordID>39215</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WIN-G8C2WZ0NU2.corp.avanade.org</Computer>
    <Security />
  </System>
  <EventData>
    <Data>MonDiag.exe</Data>
    <Data>2.0.0.0</Data>
    <Data>5bb653fd</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.16299.611</Data>
    <Data>966d0f68</Data>
    <Data>e0434352</Data>
    <Data>00104172</Data>
    <Data>1c64</Data>
    <Data>01d460cba3528ade</Data>
    <Data>C:\Users\adin.p.ermie\Downloads\MonDiag\MonDiag.exe</Data>
    <Data>C:\windows\System32\KERNELBASE.dll</Data>
    <Data>966f1fe9-9573-4d88-a6de-fc5b8d41ad39</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by prchanda** [comment]
Error while closing the AAD auth prompt without completing the sign-in process is resolved now in the new version 2.1.0... 

For the other issue where you are getting an error while login using Live ID (i.e @outlook.com) is not replicating at my end - Do you have azure subscription id associated with that Live ID ? Are you able to login to the azure portal using the same ID ?

I tried to repro the issue at my end using my Live ID (outlook.com) and the resources are getting populated as expected.

**Comment by AErmie** [comment]
Yes, I have an Azure subscription associated with both accounts (the corporate credentials, and the @outlook.com account). 

I don't even get to the resource replication point, as I encounter the error when attempting the sign-in using the @outlook.com credentials.

**Comment by prchanda** [comment]
>           Yes, I have an Azure subscription associated with both accounts (the corporate credentials, and the @outlook.com account).
> I don't even get to the resource replication point, as I encounter the error when attempting the sign-in using the @outlook.com credentials.

Please follow the below action plan and let me know what you see at your end:

1. Login to Azure Portal using Live ID.
2. Hover your mouse on your account info (top-right corner of the portal)
3. Make a note of the directory name as highlighted below in red:

![image](https://user-images.githubusercontent.com/35064849/46918245-7c098e80-cfed-11e8-9df9-e85b8fed07fb.png)

4. Fire up your browser and navigate to the below url. Replace the place holder **{directory name}** with the one which you got in step 3.

https://login.microsoftonline.com/{directory name}.onmicrosoft.com/.well-known/openid-configuration

5. You will get a JSON output like below. Are you able to see your tenant in "authorization_endpoint" ?

![image](https://user-images.githubusercontent.com/35064849/46918367-16b69d00-cfef-11e8-90af-5dd650d4783d.png)

**Comment by prchanda** [comment]
>           Yes, I have an Azure subscription associated with both accounts (the corporate credentials, and the @outlook.com account).
> I don't even get to the resource replication point, as I encounter the error when attempting the sign-in using the @outlook.com credentials.

I believe I have figured out the issue... It seems like authentication is failing for Live IDs consisting of dots... I have fixed the issue and pushed the latest release.. Please download the latest version and let me know how it goes..

Temporarily closing this thread, if the sign-in stills, please do let me know, I will reopen the issue.
